version: 0.2

env:
  variables:
    ACCOUNT_ID: 223938610529
    AWS_REGION: us-east-1
    IMAGE_NAME: wordpress-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 223938610529.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo Writing image definitions...
      - printf '[{"name":"wordpress-app","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:latest"}]' $ACCOUNT_ID $AWS_REGION $IMAGE_NAME > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
