version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 223938610529.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wordpress-app .
      - docker tag wordpress-app:latest 223938610529.dkr.ecr.us-east-1.amazonaws.com/task2-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 223938610529.dkr.ecr.us-east-1.amazonaws.com/task2-repo:latest
      - echo Build completed on `date`
artifacts:
  files: '**/*'
