version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 223938610529.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t wordpress-app .
      - docker tag wordpress-app:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/wordpress-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/wordpress-app:latest
      - printf '[{"name":"wordpress-container","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/wordpress-app:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
